spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

openai:
  api:
    url:
    serviceKey: ${GPT_SERVICE_KEY}
